### ISSUE TITLE
Support for Garmin Forerunner 245 / 245 M

### ISSUE THREAD

**Issue by wtaverni** [danielsiwiec/waypoints-app#1]
Hi, great app. Could you add support for the Garmin Forerunner 245 / 245 M ? Thanks.

**Comment by danielsiwiec** [comment]
Done!

**Comment by wtaverni** [comment]
Great! Very appreciated!
Regards from Belgium
Wouter

Op ma 19 aug. 2019 om 18:47 schreef Dan Siwiec <notifications@github.com>
